name: 'Screenshot-taker'
description: 'Takes a screenshot of any website provided the url and options and upload it as artifact'
inputs:
  url:
    description: 'The website url'
    required: true
  screenshot_name:
    description: 'The screenshot name. also the artifact name'
    required: true
  authorization_token:
    description: 'An authorization token: optional'
    required: false
    default: ''
outputs:
  path:
    description: 'Path of the screenshot'
  screenshot_name:
    description: 'Name of the screenshot'

runs:
  using: 'node16'
  main: 'dist/index.js'